Issue 1
LionelMN/Proyecto-node-mongo-nginx pull request #4
Opened 2020-10-31 11:27 UTC by LionelMN

Realizado API Node con conexión a Mongo:
- Métodos: getAllTodos, getOneById, create, remove y patch.

*Se ha probado atacando una bd Mongo en local, en principio habría que cambiar la bd a la que atacaría una vez se levante el docker con mongo

2020-11-01 13:32 UTC, raulanatol requested changes

2020-11-01 13:32 UTC, raulanatol commented on Dockerfile
> +CMD ["npm", "start"]
Fíjense que github marca el final de ese fichero con un aviso:
![image](https://user-images.githubusercontent.com/2389019/97804193-2c36a800-1c46-11eb-8a8c-befabcc4056e.png)

Indicando que no han dejado una línea en blanco al final del fichero, esto suele dar problemas entre SO y en compiladores, por lo que es buena práctica dejar siempre una línea en blanco al final de los ficheros de código.

Para que esto me lo haga automático suelo usar https://editorconfig.org/ que es compatible con muchos editores y se encarga de mantener este tipo de problemas "multi-plataforma" controlados.

2020-11-01 15:27 UTC, LionelMN commented on Dockerfile
> +CMD ["npm", "start"]
Lo tendré en cuenta a partir de ahora, ya he añadido una línea en blanco al final de todos los ficheros que lo necesitaban.

2020-11-02 08:30 UTC, raulanatol approved these changes

2020-11-02 15:26 UTC, merged